language: scala
scala:
  - 2.11.12
  - 2.12.10
  - 2.13.0
jdk:
  - openjdk8

script: |
  sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: |
  sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
